apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  
spec:
  
  replicas: 35  # Number of pod replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
        - key: "low"
          operator: "Equal"
          value: "cpu"
          effect: "NoSchedule"
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
