apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-sidecar
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
    volumeMounts:
      - name: shared-logs
        mountPath: /var/log/nginx

  - name: log-writer
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - >
        while true;
        do
          echo "$(date) - Sidecar: Logging heartbeat" >> /var/log/nginx/sidecar.log;
          sleep 5;
        done
    volumeMounts:
      - name: shared-logs
        mountPath: /var/log/nginx

  volumes:
  - name: shared-logs
    emptyDir: {}

