apiVersion: v1
kind: ResourceQuota
metadata:
  name: devops-resource-quota
  namespace: devops
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 3Gi