apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  hostPath:  # For local testing only (e.g., Minikube or single-node clusters)
    path: "/mnt/data/mysql"